// generator
export const GENERATOR_TYPE = 'GENERATOR_TYPE'
export const GENERATOR_LANGUAGES = 'GENERATOR_LANGUAGES'
export const GENERATOR_LANGUAGE = 'GENERATOR_LANGUAGE'
export const GENERATOR_OPTIONS = 'GENERATOR_OPTIONS'
export const GENERATOR_VALUES = 'GENERATOR_VALUES'
export const GENERATOR_GENERATED = 'GENERATOR_GENERATED'
// generator set
export const GENERATOR_SET_TYPE = 'GENERATOR_SET_TYPE'
export const GENERATOR_SET_LANGUAGES = 'GENERATOR_SET_LANGUAGES'
export const GENERATOR_SET_LANGUAGE = 'GENERATOR_SET_LANGUAGE'
export const GENERATOR_SET_OPTIONS = 'GENERATOR_SET_OPTIONS'
export const GENERATOR_SET_GENERATED = 'GENERATOR_SET_GENERATED'
// generator run
export const GENERATOR_RUN_SET_TYPE = 'GENERATOR_RUN_SET_TYPE'
export const GENERATOR_RUN_SET_LANGUAGE = 'GENERATOR_RUN_SET_LANGUAGE'
export const GENERATOR_RUN_LANGUAGES = 'GENERATOR_RUN_LANGUAGES'
export const GENERATOR_RUN_OPTIONS = 'GENERATOR_RUN_OPTIONS'
export const GENERATOR_RUN_GENERATE = 'GENERATOR_RUN_GENERATE'
