export { format } from 'd3-format/src/defaultLocale'
export { default as arc } from 'd3-shape/src/arc'
export { default as pie } from 'd3-shape/src/pie'
export { default as extent } from 'd3-array/src/extent'
export { default as histogram } from 'd3-array/src/histogram'
export { default as scaleLinear } from 'd3-scale/src/linear'
